### ISSUE TITLE
Failed to load files from .bak modules

### ISSUE THREAD

**Issue by robnewton** [hrishikesh-k/netlify-plugin-bundle-env#1]
There are apparently `.bak` modules that have made it into the build that are not part of my repo. Code that works prior to running the build no longer works once deployed.

```
ERROR  Failed to load module from /var/task/functions/db-users/events/user.activated.bak.js Cannot find module '/var/task/functions/db-users/events/user.activated.bak.js'
Require stack:
- /var/task/node_modules/@hopdrive/hasura-event-detector/detector.js
- /var/task/node_modules/@hopdrive/hasura-event-detector/index.js
- /var/task/functions/db-users/db-users.js
- /var/task/db-users.js
- /var/runtime/index.mjs Error: Cannot find module '/var/task/functions/db-users/events/user.activated.bak.js'
Require stack:
- /var/task/node_modules/@hopdrive/hasura-event-detector/detector.js
- /var/task/node_modules/@hopdrive/hasura-event-detector/index.js
- /var/task/functions/db-users/db-users.js
- /var/task/db-users.js
- /var/runtime/index.mjs
```

The actual file is `/var/task/functions/db-users/events/user.activated.js`. There should be no files with `.bak` included in the filename.

**Comment by hrishikesh-k** [comment]
The plugin runs on [two build events](https://docs.netlify.com/integrations/build-plugins/create-plugins/#plug-into-events), `onPreBuild` and `onEnd`. The former creates those `.bak` files, which is used to restore the original files after processing and are then deleted. The restoration is done during `onEnd`, which according to Netlify documentation, should run after the entire build process is done (regardless of the stage).

So the part that's surprising me is, why your build process is looking for that file? There should be no reason to search for those `.bak` files by your build process as they mean nothing for your build pipeline.

Based on the stack trace, it appears to be happening inside your functions, and the only thing I can imagine right now is something in your build process listing all the files available in your functions folder and generating some sort of a manifest using which it's trying to import those files.

This is just an initial thought, I'll investigate more soon.

> `/var/task/node_modules/@hopdrive/hasura-event-detector/detector.js`

That line is a little suspicious as well. Looks like some kind of filesystem detector?

**Comment by hrishikesh-k** [comment]
I'm unable to find where `@hopdrive/hasura-event-detector/detector.js` is coming from. Do you know what's the name of the module that's using that file, or is it a custom file?

**Comment by robnewton** [comment]
That’s a file from within one of our private packages listed in our package
json

Rob

**Comment by hrishikesh-k** [comment]
I thought so. So it sounds like, that file is doing something like scanning all the files in your functions_dir, and later requiring those. But since those files are never bundled (and even deleted after the build), they're missing.

I guess, a workaround would be to create those backup files somewhere outside of the functions folder. Does that sound like something that could work for your case?

**Comment by robnewton** [comment]
Yeah we are doing some less conventional requires of files within that
Netlify functions directory for more dynamic code execution. That said this
is code that has worked fine prior to this so it’s likely that what we are
doing works fine normally but is incompatible with the file treatment of
this plugin.

While I don’t think I can post the code here I’d be happy to jump on a
video call to troubleshoot it if the use case is helpful to get this
package improved.

Otherwise it seems like I might need to go back to using the other env bar
inline package even tho it had leftover changes to the source files after
builds.

Rob

**Comment by hrishikesh-k** [comment]
In that case, the current "temporary" workaround would be to add something like:

```toml
[functions]
  included_files = ["./netlify/functions/**.bak"]
```

...to your `netlify.toml`. The above example assumes that your function files are stored in `./netlify/functions` directory, and if they're not, feel free to change the value. Note that, this would bundle your "backed-up" source code of your functions along with your function bundle. Not that anyone can access the bundle (and even if they did, they'd be able to see the bundled code anyways, so it won't be much different from accessing the source), so you should not be worried about it.

I'll try adding a configurable option to backup the function files elsewhere to accommodate this use case.

**Comment by robnewton** [comment]
I don't want or need any references to bak files. I am not sure why I would
want to include them in the bundles. Are these being generated by your
plugin?

**Comment by hrishikesh-k** [comment]
> I don't want or need any references to bak files.

Like you mentioned:

> Yeah we are doing some less conventional requires of files within that Netlify functions directory for more dynamic code execution.

...your custom code is doing something that's referencing those `.bak` files.

> I am not sure why I would want to include them in the bundles.

That's a temporary workaround so that your function doesn't fail during execution.

> Are these being generated by your plugin?

Yes, I mentioned this above here:

> The former creates those .bak files, which is used to restore the original files after processing and are then deleted.

---

The long-term solution would be the plugin adding a customisable backup-dir. So the `.bak` files would be created in this separate folder outside of your Functions directory. This should help use cases like yours to not have those `.bak` files in the Functions directory, and thus, not referenced inside your bundles. I have been sick the past 2 days and workload has been a little extra too, so haven't been able to dedicate time to add that. I have laid some groundwork though.

In any case, PRs are always welcome!

**Comment by robnewton** [comment]
Thanks for all of your work on this. I too have been pretty swamped lately
and simply haven’t had the time to dedicate to troubleshooting this. I’m
sure you’re right and it’s likely my fault somehow but I just went back to
the other inline env plugin for now since it is working. I’ll revisit this
one when I have more time to dedicate to it.

Thanks again
Rob

**Comment by hrishikesh-k** [comment]
I am very close to releasing a fix for this. v0.3.0 should now include a `backup-dir` as a configurable option, which you can use to save the backup to a different folder than your Functions folder.

If all goes well, this should be released today or tomorrow. Just writing some final lines and then need to test it all.

**Comment by hrishikesh-k** [comment]
Released: https://github.com/Hrishikesh-K/netlify-plugin-bundle-env/releases/tag/v0.3.0

Closing the issue for now, feel free to re-open if that doesn't work as per your requirements. Note that, you'll have to install it from NPM till I get it updated in the Integrations Hub.
