### ISSUE TITLE
No source directory is specified

### ISSUE THREAD

**Issue by jbojcic1** [hrishikesh-k/netlify-plugin-bundle-env#3]
we are running next.js site on Netlify and I have a GOOGLE_CLOUD_KEY that is used on the server side and is pretty big thus I want to inline it. However I am constantly getting failure message from the plugin. Details:
```
7:59:39 PM: Plugin "netlify-plugin-bundle-env" failed                     
7:59:39 PM: ────────────────────────────────────────────────────────────────
7:59:39 PM: ​
7:59:39 PM:   Error message
7:59:39 PM:   Error: No source directory is specified.
7:59:39 PM: ​
7:59:39 PM:   Plugin details
7:59:39 PM:   Package:        netlify-plugin-bundle-env
7:59:39 PM:   Version:        0.4.0
7:59:39 PM:   Repository:     git+https://github.com/Hrishikesh-K/netlify-plugin-bundle-env.git
7:59:39 PM:   npm link:       https://www.npmjs.com/package/netlify-plugin-bundle-env
7:59:39 PM:   Report issues:  https://github.com/Hrishikesh-K/netlify-plugin-bundle-env/issues
7:59:39 PM: ​
7:59:39 PM:   Error location
7:59:39 PM:   In "onPreBuild" event in "netlify-plugin-bundle-env" from netlify.toml and package.json
7:59:39 PM: ​
7:59:39 PM:   Resolved config
7:59:39 PM:   build:
7:59:39 PM:     base: /opt/build/repo/apps/my-app
7:59:39 PM:     command: pnpm prepare-deploy
7:59:39 PM:     commandOrigin: ui
7:59:39 PM:     environment:
7:59:39 PM:       - GOOGLE_CLOUD_KEY
7:59:39 PM:       - IDENTITY_SERVER_CLIENT_SECRET
7:59:39 PM:       - NEXTAUTH_SECRET
7:59:39 PM:       - NEXTAUTH_URL
7:59:39 PM:       - NEXT_PUBLIC_FIREBASE_API_KEY
7:59:39 PM:       - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
7:59:39 PM:       - NEXT_PUBLIC_GOOGLE_PROJECT_ID
7:59:39 PM:       - NEXT_PUBLIC_IDENTITY_SERVER_URL
7:59:39 PM:       - NEXT_PUBLIC_ORIGIN
7:59:39 PM:       - NEXT_PUBLIC_PERSONA_ENVIRONMENT
7:59:39 PM:       - NODE_VERSION
7:59:39 PM:       - NPM_TOKEN
7:59:39 PM:       - REVIEW_ID
7:59:39 PM:       - PROJECT_NAME
7:59:39 PM:       - NEXT_PRIVATE_TARGET
7:59:39 PM:     ignore: exit 1
7:59:39 PM:     publish: /opt/build/repo/apps/my-app/out/.next
7:59:39 PM:     publishOrigin: ui
7:59:39 PM:   plugins:
7:59:39 PM:     - inputs: {}
7:59:39 PM:       origin: config
7:59:39 PM:       package: "@netlify/plugin-nextjs"
7:59:39 PM:     - inputs: {}
7:59:39 PM:       origin: config
7:59:39 PM:       package: ../../tools/plugins/netlify/netlify-stop-build
7:59:39 PM:     - inputs: {}
7:59:39 PM:       origin: config
7:59:39 PM:       package: ../../tools/plugins/netlify/netlify-plugin-set-env-vars
7:59:39 PM:     - inputs:
7:59:39 PM:         debug: true
7:59:39 PM:       origin: config
7:59:39 PM:       package: netlify-plugin-bundle-env
```

My netlify.toml looks like:
```
[build]
  ignore = "exit 1"

[build.environment]
  PROJECT_NAME = "my-app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "../../tools/plugins/netlify/netlify-stop-build"

[[plugins]]
  package = "../../tools/plugins/netlify/netlify-plugin-set-env-vars"

[[plugins]]
  package = "netlify-plugin-bundle-env"
  [plugins.inputs]
    directories = []
    include = ["GOOGLE_CLOUD_KEY"]
    debug = true
```

**Comment by hrishikesh-k** [comment]
That appears to be coming from here: https://github.com/Hrishikesh-K/netlify-plugin-bundle-env/blob/main/src/index.ts#L88-L94. Based on the TOML that you've shared, you've set the directories to `[]`:

> [plugins.inputs]
> directories = []

Then the plugin checks for functions dir, which could also be unset for your website. But since you're trying to use this in a Next.js website, it's unlikely you want this to be your functions directory either.

The `directories` should contain the directory(ies) that you wish to process. For example, if your file in which the environment variable exists is at `./src/pages/foo.tsx`, then you need to set directories as `["./src"]` OR `["/.src/pages"]`.

**Comment by jbojcic1** [comment]
@Hrishikesh-K I see. In my case I have a folder `./lib/config` which has two files public-config.ts and server-config.ts. is there a way to inline the wanted var only in the server-config.ts file or I will have to split them into separate directories?

asking because I must not have it added to the public-config.ts as that file is bundled with code that gets shipped to the client

**Comment by hrishikesh-k** [comment]
You can specify just the lib/config folder, the plugin will only work on the files that have an environment variable. If the file you don't wish to process has some environment variables, you can add those variables to the exclude list.

**Comment by jbojcic1** [comment]
@Hrishikesh-K so if my public-config contains any other env var it will still be included no matter if the var it contains is not the one I want inlined?

**Comment by hrishikesh-k** [comment]
The plugin will currently work as follows:

1. Scan the directories listed and find the files to process based on the extensions configured.
2. In each of the file that's found, it will inject all the variables available in process.env apart from the ones in the exclude list.
3. However, if you configure the include list, the plugin will only add the variables that are added to that list.

So in your case, you can make use of this exclude/include config to achieve the desired result. If it's absolutely necessary, I can try adding a files configuration option to specify the files to work on instead of just the directories, but can't say when I can do that.

**Comment by jbojcic1** [comment]
> 1. Scan the directories listed and find the files to process based on the extensions configured. 2. In each of the file that's found, it will inject all the variables available in process.env apart from the ones in the exclude list. 3. However, if you configure the include list, the plugin will only add the variables that are added to that list.

I have the include option configured as shown above but the problem is that I want that included only in one file

**Comment by jbojcic1** [comment]
I think I will work around this by putting my server-config.ts in the dedicated folder but I think adding an option to specify files instead of dirs makes sense

**Comment by jbojcic1** [comment]
@Hrishikesh-K one more question. Should the plugin remove the env var from the env vars after inlining it?

Because my deploy to Netlify still fails as the big var doesn't seem to be removed despite inlining so my deploy to netlify fails due to exceeded total limit of 4KB

**Comment by hrishikesh-k** [comment]
The plugin has no ability to remove the environment variables. Most of what we have discussed has been included in the readme: https://github.com/Hrishikesh-K/netlify-plugin-bundle-env#supports, quoting:

> Note that, the plugin is only really useful when you use the scoped environment variables feature. If you do not, all variables from the UI are published to AWS Lambda, thus rendering this plugin useless.

I'll try adding the files option, but I have a few busy weeks ahead, so I'm not sure how soon that can be done.

**Comment by hrishikesh-k** [comment]
Added the `files` option: https://github.com/Hrishikesh-K/netlify-plugin-bundle-env/releases/tag/v0.5.0

**Comment by jbojcic1** [comment]
> The plugin has no ability to remove the environment variables. Most of what we have discussed has been included in the readme: https://github.com/Hrishikesh-K/netlify-plugin-bundle-env#supports, quoting:
> 
> > Note that, the plugin is only really useful when you use the scoped environment variables feature. If you do not, all variables from the UI are published to AWS Lambda, thus rendering this plugin useless.

Yeah I saw that eventually and was able to solve by scoping the google variable to build only.

> Added the files option: https://github.com/Hrishikesh-K/netlify-plugin-bundle-env/releases/tag/v0.5.0

Wow, that was quick. Thx
