### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by 1-800-jono** [hrishikesh-k/netlify-plugin-bundle-env#6]
I keep getting `Unexpected end of JSON input` error - already checked the JSON with a validator. Everything seems fine not sure what else to do here. If I `console.log(process.env.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS)` all I see is `{`

```
 [[plugins]]
  package = "netlify-plugin-bundle-env"
  [plugins.inputs]
    debug = true
    include = ["GOOGLE_SERVICE_ACCOUNT_CREDENTIALS"]
    quiet  = true # verbose = "true"
```

Looking at netlify's function logs I see: 
```
05:42:07 PM: 2024-03-20T20:42:07.057Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.UserCodeSyntaxError","errorMessage":"SyntaxError: Unexpected token u in JSON at position 0","stack":["Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token u in JSON at position 0","    at _loadUserApp (file:///var/runtime/index.mjs:1084:17)","    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)","    at async start (file:///var/runtime/index.mjs:1282:23)","    at async file:///var/runtime/index.mjs:1288:1"]}
```

<img width="392" alt="image" src="https://github.com/hrishikesh-k/netlify-plugin-bundle-env/assets/1545577/08755070-a70c-4512-bdf3-8972a8a4aa83">

**Comment by hrishikesh-k** [comment]
Mind helping with a site or a deploy ID?

**Comment by 1-800-jono** [comment]
hi @hrishikesh-k, I ended up splitting the big `env.var` (Google api credentials). One half hardcoded and the other half in Netlify's UI.
